# Generated by Django 4.0.4 on 2022-05-28 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_pythoncode_done_pythoncode_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pythoncode',
            old_name='done',
            new_name='Done',
        ),
        migrations.RenameField(
            model_name='pythoncode',
            old_name='feedback',
            new_name='Feedback',
        ),
    ]
