# Generated by Django 4.0.4 on 2022-05-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_rename_done_pythoncode_done_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pythoncode',
            name='Feedback',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
