# Generated by Django 4.0.4 on 2022-05-31 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_alter_pythoncode_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pythoncode',
            name='username',
        ),
    ]
